model_cfg:
  pretrained_dinov2: /home/jiezhu/Desktop/code/cvpr-lsf/WBModules/msu_big_gait/pretrained_LVMs/dinov2_vits14_pretrain.pth                  # pretrain DINOv2_small
  # pretrained_dinov2: pretrained_LVMs/dinov2_vitl14_pretrain.pth                 # pretrain DINOv2_large
  pretrained_mask_branch: None
  # pretrained_mask_branch: pretrained_LVMs/MaskBranch_vits14.pt                # load pretrain Mask_Branch
  # image_size: 224                                                               # 448x224
  image_size: 448                                                             # 896x448
  sils_size: 32                                                                 # 64x32

  Denoising_Branch:
    source_dim: 1536    # DINOv2_small
    # source_dim: 4096  # DINOv2_large
    target_dim: 16
    p: 0
    softmax: True
    Relu: True
    Up: False

  Appearance_Branch:
    source_dim: 1536
    # source_dim: 4096
    target_dim: 16
    p: 0
    softmax: False
    Relu: False
    Up: False

  Mask_Branch:
    source_dim: 384       # DINOv2_small
    # source_dim: 1024    # DINOv2_large
    target_dim: 2
    p: 0.5
    softmax: True
    Relu: False
    Up: True

  AttentionFusion:
    in_channels: 64
    squeeze_ratio: 16
    feat_len: 2

  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    in_channel: 1
    channels: # Layers configuration for automatically model construction
      - 64
      - 128
      - 256
      - 512
    layers:
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 100  #: training sample numbers
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16